bind r source-file ~/.config/tmux/tmux.conf

# remove delay when hitting ESC
set -s escape-time 0

set -g mouse on

unbind M-a
set -g prefix M-a
bind M-a send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

bind -n M-n next-window
bind -n M-p previous-window

# Status bar
set-option -g status-style "bg=#f0edec,fg=#191919"
set-option -g status-position top
set-option -g status-left-length 20
set-option -g status-left "#[bg=#61abda,fg=#191919] #S #[fg=#191919,bg=#f0edec]|"
set-option -g status-right "#[bg=#957fb8,fg=#191919] %H:%M "
set-window-option -g window-status-current-style "bg=#98bb6c, fg=#191919"
set-window-option -g window-status-current-format " #I #W "
set-window-option -g window-status-format " #I #W "

bind -n M-h select-pane -L  # move left
bind -n M-j select-pane -D  # move down
bind -n M-k select-pane -U  # move up
bind -n M-l select-pane -R  # move right
